--[[
	Package link auto-generated by Kayak
]]

local PackageIndex = script.Parent._index

local package = PackageIndex["osyris_t"]["t"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package